### ISSUE TITLE
Unable to start using unRaid template

### ISSUE THREAD

**Issue by trashken** [Dark-Alex-17/managarr#13] opened 2024-11-05 04:15 UTC
Error: No such device or address (os error 6)

**Comment by Dark-Alex-17** [comment] 2024-11-06 00:08
I think I need more information on how this error happened. Were you specifying a config file via `--config`? If so, it could mean that the file you're pointing to is missing or the drive it's on is unmounted, or perhaps there's permission issues opening the file?

**Comment by trashken** [comment] 2024-11-11 07:07
It's thru the Unraid template. The config is configured to the host path below: 

/mnt/user/appdata/managarr/config

The container path is /root/.config/managarr

**Comment by Dark-Alex-17** [comment] 2024-11-11 19:05
I'm struggling to replicate this issue. So my questions so far are:

* Are you using the latest image of Managarr?
* Do you have the permissions configured correctly for the directory? i.e. is your `$USER` authorized to both access the directory, and does the config file have read permissions?
* Can you share your exact docker run command, if it's any different from the main one in the `README`?
* Is this error showing up in the TUI or logs, or does it happen when you try to start `managarr` in the TUI, but it never starts because of this error?

**Comment by btTeddy** [comment] 2024-11-15 14:02
Same issue in here.
Used all the defaults from CA store template, nothing changed.

First start (without editing the config) ends with this error
![image](https://github.com/user-attachments/assets/91e50f3e-40d2-4df0-a6c5-3746d3485b59)

Once config updated, the error remains. 
Container will not start. 
Only log info is the above `Error: No such device or address (os error 6)`


config file was automatically created in `/mnt/user/appdata/managarr/config/config.yml`


![image](https://github.com/user-attachments/assets/cf777570-167b-4820-8b46-b1b1a4d12eb0)


`config.yml` content
```radarr:
  host: <radarr_IP>
  port: 7878
  uri: null
  api_token: '<REDACTED>'
  ssl_cert_path: null
```

**Comment by Jmainguy** [comment] 2024-11-16 13:53
from the GPT's

### Diagnosing "No such device or address (os error 6)"

The error message "No such device or address (os error 6)" typically indicates that the application is trying to access a file or device that does not exist or is not accessible at the specified path. Here are a few potential causes and solutions you might consider:

1. **File Path Verification**:
   - Ensure that the file path `/mnt/user/appdata/managarr/config/config.yml` is correct and that the file actually exists at that location. You can do this by logging into the unRaid server and using commands like `ls` to verify the presence of the file.

2. **Permissions**:
   - Check the permissions of the file and the directories leading up to it. The user running the application must have read permissions for the file and execute permissions for the directories. You can use the `ls -l` command to check permissions and `chmod` to modify them if necessary.

3. **Mount Points**:
   - Verify that the `/mnt/user/appdata` directory is properly mounted. If this is a network share or a special mount point, ensure that it is mounted correctly and accessible.

4. **Symbolic Links**:
   - If any part of the path is a symbolic link, ensure that the link is not broken and points to the correct location.

5. **Application Configuration**:
   - Double-check your application's configuration to ensure that it is correctly set to read from the specified path. There might be a configuration option or environment variable that is not set correctly.

6. **Environment Differences**:
   - Consider any differences in the environment where the application works versus where it doesn't. This could include differences in the file system, user permissions, or network configurations.

7. **Logging**:
   - Add additional logging to your application to capture more details about the error. This might include logging the exact path being accessed and any relevant environment variables.

If none of these suggestions resolve the issue, you might want to replicate the environment as closely as possible on a test system to see if you can reproduce the error and gather more information.

**Comment by Heavensong89** [comment] 2024-11-20 07:30
same error here with the below
![image](https://github.com/user-attachments/assets/1f8af30a-00a8-4c25-b216-cd2000b09116)

`Error: No such device or address (os error 6)`

**Comment by Dark-Alex-17** [comment] 2024-12-14 04:21
This may or may not be related, but I did just manage to recreate this issue by accident. I get the exact same error whenever I attempt to start the container with out the '-t' flag, meaning this issue is not necessarily caused by the config as I originally thought. It may be that you need to somehow specify the `-t` flag to indicate to Docker that you want to allocate a pseudo-TTY.

Unfortunately I don't have unRaid so I can't test it myself, but as far as I can tell this seems possible.

**Comment by Dark-Alex-17** [comment] 2024-12-14 04:21
This may or may not be related, but I did just manage to recreate this issue by accident. I get the exact same error whenever I attempt to start the container with out the '-t' flag, meaning this issue is not necessarily caused by the config as I originally thought. It may be that you need to somehow specify the `-t` flag to indicate to Docker that you want to allocate a pseudo-TTY.

Unfortunately I don't have unRaid so I can't test it myself, but as far as I can tell this seems possible.

**Comment by Heavensong89** [comment] 2024-12-14 10:55
![image](https://github.com/user-attachments/assets/439f001b-c9df-46bb-b71c-28ab018094e0)
need to add "-it" or "--interactive -tty" to the 'Extra Parameters' in Unraid. I'm not sure who owns the Unraid CA Template for managarr to suggest the edit to them.

**Comment by diabillic** [comment] 2024-12-14 20:25
confirming adding the interactive switch on the unraid template fixes this issue

**Comment by Dark-Alex-17** [comment] 2024-12-17 22:54
I'd like to close this issue, but I don't want to until we can confirm that whoever owns the unRaid template has updated this. 

Also, given that I know next to nothing about unRaid, is it possible to have the template saved here in the repo and also deploy it whenever changes might need to be made? That way we can have an official unRaid template for it and avoid a similar issue.

**Comment by nwithan8** [comment] 2024-12-30 22:16
Thanks @Dark-Alex-17 for letting me know, the fix has been merged and should populate on the Unraid store in a few hours.

**Comment by Dark-Alex-17** [comment] 2024-12-30 22:17
Thanks @nwithan8 ! To everyone on this thread who's using the template, please let me know if it's working now. If it is, I'll close this issue and update the README.

**Comment by nwithan8** [comment] 2024-12-30 22:23
> Also, given that I know next to nothing about Unraid, is it possible to have the template saved here in the repo and also deploy it whenever changes might need to be made? That way we can have an official Unraid template for it and avoid a similar issue.

We can move the template over here if you'd like. You would need to register this as an Unraid template repository, which involved joining the Unraid forum and contacting "Squid".

If not, feel free to always open a PR on the template in my general repo.

**Comment by Dark-Alex-17** [comment] 2024-12-30 23:28
That might be easier if ever I add something else and need to add additional options to the container. Is there any deployment steps to get the template out there or anything like that?

**Comment by nwithan8** [comment] 2024-12-30 23:33
> That might be easier if ever I add something else and need to add additional options to the container. Is there any deployment steps to get the template out there or anything like that?

Nope, just need to have your repository added to the list of Unraid community app sources by Squid. The store pulls in any new or changed templates every two hours.

**Comment by Dark-Alex-17** [comment] 2024-12-31 01:40
Oh sweet! Would I basically just mimic your repo's directory structure with the template file? Anything else I'd need to add?

**Comment by nwithan8** [comment] 2024-12-31 04:38
> Oh sweet! Would I basically just mimic your repo's directory structure with the template file? Anything else I'd need to add?

Full instructions here: https://forums.unraid.net/topic/87144-ca-application-policies-notes/

**Comment by Dark-Alex-17** [comment] 2024-12-31 22:52
Since this is fixed now, I'm going to close this issue. For the time being, since it seems there's no further changes really needed in the foreseeable future for publishing versions, I don't see any issue having the official template live in your repo's @nwithan8 .

That said, once I have a bit of time, I'm going to come back and get this repo set up to be the official home for the Managarr template. I'll coordinate with you as needed when I get to that point. Thanks for the help!

**Closed** 2024-12-31 22:52 UTC
